genaray/Arch

Arch.Test/Arch.Test.csproj
Arch.Test/CommandBufferTest.cs
Arch.Test/QueryTest.cs
Arch/Core/Archetype.cs
Arch/Core/CommandBuffer/CreationBuffer.cs
Arch/Core/CommandBuffer/DestructionBuffer.cs
Arch/Core/CommandBuffer/ModificationBuffer.cs
Arch/Core/CommandBuffer/StructuralBuffer.cs
Arch/Core/Enumerators.cs
Arch/Core/Extensions/ArrayExtensions.cs
Arch/Core/Utils/CompileTimeStatics.cs
Arch/Core/Utils/LookupArray.cs
Arch/Core/World.cs

Final draft of the command buffer API to buffer entity changes to play them back at a desired moment.
Also adds several other small util methods, classes and even more parallel query overloads, targets #17.
```csharp
var creationBuffer = new CreationBuffer(world, 1024); <- Initial capacity, not total capacity 
world.ParallelQuery(in desc, (in Entity en) => {
var entity = creationBuffer.Create(group); 
entity.Set<Explosion>(...);
entity.Set<Position>(...);
});
creationBuffer.Playback();
```

Command buffer

---

Arch/Core/World.cs

This is an hack to set the entity 8 bytes aligned and should help in terms of performances [I didn't test tbh].
In addition the `Null` entity will be created just one time now

Entity struct padding to fit 8 bytes size

---

Arch.SourceGenerator/Queries/HPQueryExtensions.cs
Arch.SourceGenerator/Queries/JobExtensions.cs
Arch.SourceGenerator/Queries/QueryExtensions.cs
Arch/Core/Jobs/Jobs.cs
Arch/Core/World.cs
README.md

This solve https://github.com/genaray/Arch/issues/13
The problem was with the line:
`var destroyedChunk = archetype.Remove(ref entityInfo.Slot, out var movedEntityId);`
which moves the last entity to the destroyed entity index.
When this happens `in Entity` [which is translated into `ref readonly Entity`] changes the reference to the moved entity, so Arch will recycle a valid ID.
Tested with the code below [and some other variations]
```csharp
struct P { }
var world = World.Create();
var query = new QueryDescription()
{
All = new Core.Utils.ComponentType[] { typeof(P) },
};
for (int i = 0; i < 100; ++i)
world.Create<P>();
while (true)
{
world.Query(in query, (in Entity e) =>
{
world.Destroy(in e);
var ee = world.Create<P>();
});
}
```

Support entity creation/deletion during a query

---

src/Arch/Core/Utils/EntityDebugView.cs

Without it, GetAllComponents (line 21), IsAlive (line 32) and WorldId (line 47) result in a compilation error since those are only available without PURE_ECS

Hide EntityDebugView behind !PURE_ECS

---

src/Arch/Core/Utils/SkipLocalsInit.cs

This causes errors for other projects on or above C# 9 that are using the original one, since SkipLocalsInit has a duplicate definition.
The other two fixes I could find are using reference aliases (see https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0433), or propagating the attribute redefinition upwards.
I'm unsure if this breaks skipping local init, since Rider has a bug where it won't show that properly in its IL viewer (see https://youtrack.jetbrains.com/issue/RIDER-90904), this can be checked with ildasm.exe though.

Make SkipLocalsInit internal

---

src/Arch/Core/World.cs

Under regular use the elements are never null, they are only set to null when clearing or disposing the collection (on World.Clear and World.Destroy).
This PR instead ignores the nullability warning when setting the elements to null in those places, since they become inaccessible immediately after and are only used to make sure the memory gets freed.
This fixes a couple warnings:
Also fixes two nullability warnings in methods using TryGetValue

Make World.Archetypes elements non-nullable and fix TryGetValue nullability

---

src/Arch/Core/Entity.cs

It causes a compilation error with PURE_ECS enabled otherwise.
The method signature was changed in eb47ee37d1621a8649d331dc637216808222648a

Remove leftover `in` from world.Reference(Entity) call

---

src/Arch/Core/Pollyfilling/SkipLocalsInit.cs
src/Arch/Core/Pollyfilling/UnscopedRef.cs

See the docs for [SkipLocalsInit](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.skiplocalsinitattribute?view=net-8.0) and [UnscopedRef](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.unscopedrefattribute?view=net-8.0)
Also fixes some warnings about these attributes being duplicated.

Add version preprocessor to SkipLocalsInit and UnscopedRef

---

src/Arch/Core/Entity.cs
src/Arch/Core/World.cs

I found that `IsAlive()` on a reference to a deleted entity was returning `true`, leading to my code crashing.
I think the problem is that:
- `IsAlive()` does a version check by comparing `this` with `Entity.Reference()`. So if `Reference()` returns null or a different version, `IsAlive()` will be false (so far so good...)
- `Reference()` returns version `0` when an entity with a matching id is not found.
- So if you have a reference to version `0` of an entity, `IsAlive()` will always return `true` for it.
I fixed my problem by making `Reference()` return `EntityReference.Null` when an entity is not found.
This had the follow-on problem that `IsAlive()` would return `true` for `EntityReference.Null`, so I added a special case for that.

IsAlive on dead reference should be false

---

src/Arch/Core/Entity.cs

Makes all calls to methods that take in an Entity easier if the value referenced is coming from a component, where `EntityReference` is supposed to be used instead of Entity.
For example:
```csharp
ref var map = ref World.TryGetRef<MapComponent>(mapId, out var exists);
```
Instead of:
```csharp
ref var map = ref World.TryGetRef<MapComponent>(mapId.Entity, out var exists);
```

Add an implicit conversion operator for EntityReference > Entity

---

src/Arch/Core/Chunk.cs

Prevents for example all running tests from crashing if one of them tries to get a type that doesn't exist in a chunk, if building on Debug.

Add Debug.Assert for chunk array index being out of bounds

---

src/Arch/Core/Utils/CompileTimeStatics.cs

This fixes a crash when adding a component with type id 0 to an entity, for example through world.Create(in comp).
If comp has a type id of 0 then an error is thrown when trying to index that type in the chunk, since the archetype retrieved for that type is the one associated with a component type hash of 0, which is the empty one.
I didn't make line 155 use Size++ so that the state doesn't get corrupted if _types.Add throws for some reason, since even though it checks at the start of the method I don't think it's made to be thread safe.

Offset all component type ids by +1

---

src/Arch/Core/World.cs

Missed this in https://github.com/genaray/Arch/pull/92
Checked the rest of the Add and AddRange methods and they look correct

Fix World.AddRange with a Span<object> not adding the components after the archetype move

---

src/Arch.SourceGen/Fundamentals/Create.cs
src/Arch.SourceGen/Fundamentals/Set.cs
src/Arch.SourceGen/Fundamentals/StructuralChanges.cs
src/Arch.Tests/EventTest.cs
src/Arch/Core/Events/EventHandlers.cs
src/Arch/Core/Events/EventTypeRegistry.cs
src/Arch/Core/Events/Events.cs
src/Arch/Core/Events/World.Events.cs
src/Arch/Core/Extensions/WorldExtensions.cs
src/Arch/Core/World.cs

Closes https://github.com/genaray/Arch/issues/104
Some calls still contain the preprocessor since they do more than just call the event method.
Using [Conditional("EVENTS")] instead does not seem to work.

Move if EVENTS preprocessor to the event methods

---

src/Arch/Core/Archetype.cs
src/Arch/Core/Chunk.cs
src/Arch/Core/Extensions/WorldExtensions.cs
src/Arch/Core/World.cs

From https://github.com/genaray/Arch/pull/103
Some of these result in substantially better performance for single component World.Add calls.

Remove unnecessary ComponentType lookups

---

src/Arch/Core/Archetype.cs
src/Arch/Core/Edges/Archetype.Edges.cs
src/Arch/Core/Extensions/Internal/ArrayExtensions.cs
src/Arch/Core/Utils/ArrayDictionary.cs
src/Arch/Core/World.cs

Closes https://github.com/genaray/Arch/issues/115
This PR also fixes a bug where archetype edges would sometimes not be added if the array had already been resized to be bigger than the new component id.
Two paths are necessary for netstandard2.0, as it is not possible to get a ref from a dictionary before .NET 5.
ArrayDictionary is made internal as well, since that is a data structure intended to be used by Arch only.
Remove edges will be implemented later as well, where it caches the resulting archetype from component removals.

Move archetype edge logic to the Archetype class

---

src/Arch/Core/Chunk.cs

The one added in https://github.com/genaray/Arch/commit/3da792f463b924d06978ef2f914ac56e23b5c37e doesn't account for a component type that both exists and is within the bounds of the ComponentIdToArrayIndex array.
This would cause an AccessViolationException when the indexed component type is both registered (not -1) and is smaller than the maximum type tracked by the chunk, since the assert in Index<T> wouldn't be triggered in such a case.

Add bounds debug assert to Chunk.GetArray<T>

---

src/Arch/CommandBuffer/CommandBuffer.cs

**Bug in the `CommandBuffer`**
When the component was being set the index of the entity was used to reference the component. It produced an undesired behavior of copying the wrong data or just throwing an exception as the index was out of bounds.
**Solution**
Use indirect indexing via `SparseArray.Entities` instead as it contains an index of the component

Fix: Command Buffer accessing a component by entity id

---

src/Arch/Core/Utils/CompileTimeStatics.cs

It's not possible to have generic struct components otherwise.
This also splits the generic paths to not have to use reflection.

Replace Marshal.SizeOf with Unsafe.SizeOf for component registration

---

src/Arch/Core/Edges/World.Edges.cs
src/Arch/Core/Utils/ArrayDictionary.cs

The conditions were inverted for the max size check (256).
Also ref wasn't being used when using at leasst .NET 5, which caused another error.

Fix archetypes breaking after having more than 256 of them

---

src/Arch.Benchmarks/BitSetBenchmark.cs
src/Arch.Tests/BitSetTest.cs
src/Arch/Core/Utils/BitSet.cs
src/Arch/Core/Utils/CompileTimeStatics.cs
src/Arch/Core/Utils/MurmurHash3.cs

Realistically, many projects have a large number of components that are used. Up to 100, 200 or even more depending on the scale. 
So far, such a high number of components in the `Bitset` has caused problems. These simply checked the bits with a scalar loop. For a few used components this is fast, but for many it is quite slow and noticeable.
Therefore this PR integrates vectorized `BitSet` methods to process a high number of used components faster. This is triggered only at a certain number, if the number of registered components exceeds this, the methods are executed vectorized. If they fall under it, the execution remains scalar. Since vectorization comes along with an overhead for few elements, the best of both sides is combined.

Vectorized Bitsets

---

src/Arch/CommandBuffer/SparseSet.cs
src/Arch/Core/Chunk.cs
src/Arch/Core/Utils/CompileTimeStatics.cs

This PR adds a new ArrayRegistry class that you can use to fully support Native AOT. It would also open up the possibility of a source generator to call this for you. 
You would use this by calling `ArrayRegistry.Add<MyComponent>();` and then the chunks will try to get an array from the ArrayRegistry instead. If no component has been registered, it will default back to reflection, so no functionality is broken and you aren't forced to use this. 
Along with this change, if the user chooses to use this along with the source generators in Arch.Extended, one can achieve a fully Native AOT without ***any reflection***!

Add support for registering arrays for AOT support

---

.gitignore
Directory.Build.targets
scripts/UnityPublish.sh
src/Arch.SourceGen/Arch.SourceGen.csproj
src/Arch/Arch.csproj

At a high level, this pull request adds a `UnityPublish.sh` script that quickly and easily generates Arch DLLs (and transitive DLLs) needed for Unity, **not** including source generation. Running `./scripts/UnityPublish.sh` publishes the files to `dist/Assemblies`. The same script could be used in further automation via a GitHub Action to produce a zipped build artifact. I recommend doing so as a follow-up pull request.
Granular changes:
* `dist` was added to the `.gitignore` to keep Unity-published files out of Git history.
* A `Directory.Build.targets` file has been added to the root directory. It is configuration for defining custom targets at the solution level which override those of the encompassed project (`csproj`) configuration because MSBuild reads it in last as opposed to all …

Add (local) publishing of Arch and its transitive dependencies for Unity

---

Directory.Build.targets
scripts/UnityPublish.sh
src/Arch/Arch.csproj

This pull request fixes this problem: https://github.com/genaray/Arch/discussions/143#discussioncomment-7159775.
The tests pass while simultaneously allowing Unity publishing with `netstandard2.1`.
~~Now the `TargetFramework` for projects that otherwise didn't have it is set to `net7.0`~~ (see below comment) which will prevent the tests from failing (for that reason). `TargetFramework`, `TargetFrameworks` and `TargetFrameworkVersion` are also now forced in the `UnityPublish.sh` script as arguments, because it 100% reliably overwrites whereas putting them in `Directory.Build.targets` apparently didn't. I'm not a fan of MSBuild.
I'm additionally ensuring that any previously published assemblies are deleted before new ones are generated again just to be safe. We don't want old ones to gunk …

Ensure Unity publishing works without disrupting other targets

---

src/Arch.SourceGen/Fundamentals/Create.cs
src/Arch.SourceGen/Fundamentals/Group.cs
src/Arch.SourceGen/Fundamentals/StructuralChanges.cs
src/Arch.SourceGen/Queries/AddWithQueryDescription.cs
src/Arch.SourceGen/Queries/RemoveWithQueryDescription.cs
src/Arch.SourceGen/QueryGenerator.cs
src/Arch/CommandBuffer/CommandBuffer.cs
src/Arch/Core/Archetype.cs
src/Arch/Core/Chunk.cs
src/Arch/Core/Entity.cs
src/Arch/Core/Events/World.Events.cs
src/Arch/Core/Extensions/Dangerous/DangerousWorldExtensions.cs
src/Arch/Core/Extensions/EntityExtensions.cs
src/Arch/Core/Extensions/WorldExtensions.cs
src/Arch/Core/Jobs/Jobs.cs
src/Arch/Core/Jobs/World.Jobs.cs
src/Arch/Core/StructuralChangeAttribute.cs
src/Arch/Core/Utils/CompileTimeStatics.cs
src/Arch/Core/World.cs
src/Arch/Core/WorldExtensionsAttribute.cs

* Fixes some concurrency issues with `World` to make it thread-safe (outside of structural change and parallel query methods)
+ Of note, adds necessary locking mechanisms to World.Events.cs and `world.Query()` (the query caching behaviour)
* Annotates structural changes with `[StructuralChange]` in World.cs
* Annotates safe world extension methods with `[WorldExtension]`
* Changes World API to officially support null class components through nullables, and fixes many (not all) nullable issues in the project
* Makes `Group<T0, ...>.Hash` and `.Types` public
* Minor improvements to documentation and code style based on the current .editorconfig, mostly focusing on World.cs
* Compiler and intellisense warning fixes

World concurrency fixes, structural change annotations, and code cleanup

---

src/Arch.Tests/Arch.Tests.csproj
src/Arch/Core/Extensions/Internal/ArrayExtensions.cs
src/Arch/Core/Utils/CompileTimeStatics.cs

I started testing the `ArrayExtension` methods and discovered a bug in the `Add` and `GetOrResize` methods. Both methods internally call `Array.Resize`, but they never return the new array! This is probably because the method is very badly named and implies that it will somehow resize an existing array, this is not the case. To quote the docs:
> This method allocates a new array with the specified size, copies elements from the old array to the new one, and then replaces the old array with the new one.
---
The `GetOrResize` method was not used anywhere, so I simply deleted it.
The `Add` method was only used in the `CompileTimeStatics` class, which was using a `Type[]` as a map from `int -> Type`. Replaced this with an actual `Dictionary<int, Type>` instead, removing the need for the …

Fixed Some Array Extensions Bugs

---

src/Arch/Core/Enumerators.cs

Fixed some of the doc comments on Enumerators.
Most importantly I rewrote the `ChunkRangeEnumerator` comment, which was previously just copied from `QueryChunkEnumerator`. You'll want to pay close attention to that to make sure that the new docs are correct.

Fixed Some Doc Comments

---

src/Arch/Core/Archetype.cs
src/Arch/Core/Enumerators.cs

Added tests covering `Enumerator`. 
The `(Span<T> span, int length)` constructor makes it very easy to access out of bounds. Initially I added range checking, but I think it's neater to just remove that constructor altogether. The call site (there is only one) can slice the `Span` to the correct length.

Enumerator Tests

---

src/Arch/Core/EntityInfo.cs
src/Arch/Core/Extensions/EntityExtensions.cs
src/Arch/Core/Extensions/WorldExtensions.cs
src/Arch/Core/Utils/CompileTimeStatics.cs
src/Arch/Core/Utils/EntityDebugView.cs

The one in CompileTimeStatics is suppressed since that only happens if you explicitly remove the type yourself.
The one in EntityInfo is also as it's the filler value.

Fix leftover nullability warnings

---

src/Arch/CommandBuffer/StructuralSparseSet.cs

You wrote type.Id instead of passing along Capacity.

Fix bug in structural sparse array, resulting in massive performance loss due to reallocation. Affecting command buffer heavily.

---

src/Arch/Core/Extensions/Dangerous/DangerousWorldExtensions.cs

When loading a save using persistence, the GroupToArchetype dictionary wasn't being initialized. As such, when making any modifications after loading, duplicate archetypes are created. This was contributing to saves growing every time you serialize/deserialize a world.

fixed archetype duplication after loading a save

---

src/Arch/Core/Extensions/Dangerous/DangerousWorldExtensions.cs

Currently exposes a tuple so I didn't have to change RecycledEntity to public.

allow getting and setting of recycled entity ids for persistence

---

src/Arch.Tests/EventTest.cs
src/Arch/Core/World.cs

As raised in issue #194.
This adds the missing ComponentAdded event call when using the entity Create method that takes in `Span<ComponentType>` (which also affects the `params ComponentType[]` overload).
This PR also makes it so that destroying an entity also raises the ComponentRemoved event for each component on the entity.
This event is raised before the EntityDestroyed event.
I believe this brings it in line with the behaviour of Create raising the ComponentAdded event.
Unit tests for the new behaviour are included.
Thanks.

Fix missing component Add event, and raise Remove event when destroying entities.

---

src/Arch/Core/Extensions/Dangerous/DangerousWorldExtensions.cs

The Persistence extension was unable to load saves in .Net 2.1, due to an error caused by Unsafe.As not converting properly. This works fine in later versions of .Net, but for whatever reason fails in .Net 2.1, which is used for Unity.
This is slightly less efficient, but given how this is not a hot path it should be fine.

fixed issue with Unsafe.As not working in .Net 2.1

---

src/Arch/Core/Jobs/World.Jobs.cs

When the SharedJobScheduler is null, the exception message was wrong because it described the old method of assigning the shared instance.

Correct JobScheduler exception message.

---

src/Arch/Buffer/SparseSet.cs
src/Arch/Buffer/StructuralSparseSet.cs

It helps a lot with speed if you have CommandBuffers with a lot of things in them

Optimize clearing array by using Array.Fill

---

.github/workflows/workflows.yaml

GitHub Actions fails any flow that uses actions/upload-artifact@v3.
This pull request includes a small but important change to the `.github/workflows/workflows.yaml` file. The change updates the version of the `actions/upload-artifact` action used in the workflow.
* [`.github/workflows/workflows.yaml`](diffhunk://#diff-91e06c8e996e962256a5c34a92a1506e22be2d32bdc601694c02722a02c4fa34L57-R57): Updated the `actions/upload-artifact` action from version `v3` to `v4`.

bump actions/upload-artifact version

---

src/Arch/Core/World.cs

This PR fixes a build error when the EVENTS flag is set, by updating the reference to `arch.Types` to `arch.Signature` as recommended on Discord by clxs.

Fix EVENTS: Use arch.Signature instead of arch.Types

---

src/Arch.Tests/MultiThreadTest.cs
src/Arch/Core/World.cs

I found that World.WorldSize can have unintended value when create and destroy World multi-threaded.
Simply use Interlocked methods to solve this problem.
Also unit test added: MultiThreadTest.MultiThreadedCreateAndDestroy
Sometimes test failed before fix.

Fix thread-safety problem in World.WordSize

---

src/Arch/Templates/Components.cs
src/Arch/Templates/Components.tt
src/Arch/Templates/Helpers.ttinclude

`Components<...>` types are the perfect candidates for a [deconstructor method](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/deconstruct), especially for smaller fetches and fetches of commonly related components (Position, Rotation, Scale or Velocity, AngularVelocity, etc.)
When calling `EntityExtensions.Get<...>(this Entity entity)`, or otherwise consuming the `Components<...>` type, you can deconstruct them inline like so:
```cs
Entity entity = ...;
var (position, rotation, scale) = entity.Get<Position, Rotation, Scale>();
position.Value = ...;
rotation.Value = ...;
scale.Value = ...;
```
or
```cs
Entity entity = ...;
Velocity velocity;
AngularVelocity angularVelocity;
(veloctity, angularVelocity) = entity.Get<Velocity, AngularVelocity>();
```
etc.
The …

Add Deconstructor(...) method to generated Components<...> types

---

src/Arch.Tests/StructuralSparseArrayTest.cs
src/Arch/Buffer/StructuralSparseSet.cs

Currently, `StructuralSparseArray` is broken quite badly since the `Clear()` method doesn't empty the whole array.
Because of this, using Add and Remove in a reused CommandBuffer can occasionally corrupt the state of the world, by adding a component twice on an entity! The CommandBuffer needs to be recreated from scratch every time, because the `StructuralSparseArray` does not clear correctly.
This PR fixes the bug and adds a basic functionality test, testing operations against a control `HashSet`. The test currently fails on master, but passes after this PR.
I can't figure out how to reproduce the CommandBuffer bug for a unit test -- it only occurs in the wild after a very specific sequence of Add and Remove operations and playbacks, that I have yet to understand. But this fixes the root …

Fix StructuralSparseArray Clear function and add basic test
